title: Services
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
      -
        handle: hero
        field:
          type: section
          listable: hidden
          display: Hero
      -
        handle: hero_image
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          type: assets
          listable: hidden
          display: Image
      -
        handle: hero_header
        field:
          input_type: text
          type: text
          listable: hidden
          display: Header
      -
        handle: hero_text
        field:
          type: textarea
          listable: hidden
          display: Text
      -
        handle: lead-in
        field:
          type: section
          listable: hidden
          display: Lead-In
      -
        handle: leadin_icon
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          type: assets
          listable: hidden
          display: Icon
      -
        handle: leadin_header
        field:
          input_type: text
          type: text
          listable: hidden
          display: Header
      -
        handle: leadin_text
        field:
          type: textarea
          listable: hidden
          display: Text
      -
        handle: process
        field:
          type: section
          listable: hidden
          display: Process
      -
        handle: process_phases
        field:
          fields:
            -
              handle: icon
              field:
                mode: grid
                restrict: false
                allow_uploads: true
                type: assets
                listable: hidden
                display: Icon
            -
              handle: header
              field:
                input_type: text
                type: text
                listable: hidden
                display: Header
            -
              handle: text
              field:
                input_type: text
                type: text
                listable: hidden
                display: Text
          mode: stacked
          max_rows: 4
          min_rows: 0
          add_row: 'Add Phase'
          reorderable: true
          type: grid
          listable: hidden
          display: Phases
      -
        handle: process_header
        field:
          input_type: text
          type: text
          listable: hidden
          display: 'Sidebar Header'
      -
        handle: process_list
        field:
          type: list
          listable: hidden
          display: 'Sidebar List'
      -
        handle: process_text
        field:
          type: textarea
          listable: hidden
          display: 'Sidebar Text'
      -
        import: button
        prefix: process_
      -
        handle: feedback
        field:
          type: section
          listable: hidden
          display: Feedback
      -
        import: feedback
        prefix: feedback_
      -
        handle: form
        field:
          type: section
          listable: hidden
          display: Form
      -
        handle: form_header
        field:
          input_type: text
          type: text
          listable: hidden
          display: Header
      -
        handle: form_steps
        field:
          fields:
            -
              handle: icon
              field:
                mode: grid
                restrict: false
                allow_uploads: true
                type: assets
                listable: hidden
                display: Icon
            -
              handle: header
              field:
                input_type: text
                type: text
                listable: hidden
                display: Header
            -
              handle: text
              field:
                input_type: text
                type: text
                listable: hidden
                display: Text
          mode: stacked
          max_rows: 3
          min_rows: 0
          add_row: 'Add Step'
          reorderable: true
          type: grid
          listable: hidden
          display: Steps
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
